Implement voting
micheljung/faf-java-api pull request #210
Opened 2018-04-11 18:05 UTC by axel1200

Fixes #200

2018-04-11 20:12 UTC, axel1200 commented on src/main/java/com/faforever/api/data/domain/Vote.java
> +public class Vote extends AbstractEntity {
maybe should extend ownable something

2018-04-11 20:13 UTC, axel1200 commented on src/main/java/com/faforever/api/data/listeners/VotingChoiceEnricher.java
> +    votingChoice.setNumberOfAnswers(votingChoice.getVotingAnswers().size());
Can that be done in the getter... I wonder

2018-04-11 20:14 UTC, axel1200 commented on src/main/java/com/faforever/api/voting/VotingService.java
> +    //TODO: count only valid games
How do I do this?

2018-04-11 20:15 UTC, axel1200 commented on src/main/java/com/faforever/api/voting/VotingService.java
> +    if (gamesPlayed < subject.getMinGamesToVote()) {
should be <=

2018-04-11 20:15 UTC, axel1200 commented on src/main/java/com/faforever/api/voting/VotingService.java
> +    if (gamesPlayed < subject.getMinGamesToVote()) {
not what thats fine like this

2018-04-11 20:17 UTC, axel1200 commented on src/main/java/com/faforever/api/data/listeners/VotingChoiceEnricher.java
> +    votingChoice.setNumberOfAnswers(votingChoice.getVotingAnswers().size());
I mean I could just check but is there another way to get the game count

2018-04-11 20:39 UTC, axel1200 commented on src/main/java/com/faforever/api/voting/VotingService.java
> +    //TODO: count only valid games
I mean I could just check but is there another way to get the game count

2018-05-07 20:23 UTC, bukajsytlos requested changes

2018-06-02 14:18 UTC, Brutus5000 requested changes
This is just the first glance. I will need to go through it in detail

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/Player.java
> +public class Player extends Login implements OwnableEntity {
Remove the interface because see List<Vote>

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/Player.java
> +  private List<Vote> votes;
Remove this list. It's not wrong, but Hibernate will load it everytime we query a player and elide has to check for every entry if the requester is allowed it to be visible. The player is allowed to see his votes only, so he can query them from the Vote entity itself.

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/Player.java
> +  @ReadPermission(expression = IsEntityOwner.EXPRESSION)
Remove this as well

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/Vote.java
> +  private List<VotingAnswer> votingAnswers;
Probably use a Set instead, if we don't rely on the database order.

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/VotingAnswer.java
> +public class VotingAnswer extends AbstractEntity {
implements OwnableEntity

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/VotingQuestion.java
> +  private List<VotingChoice> votingChoices;
Probably use a Set instead, if we don't rely on the database order.

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/VotingSubject.java
> +  private List<Vote> votes;
Probably use a Set instead, if we don't rely on the database order.

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/data/domain/VotingSubject.java
> +  private List<VotingQuestion> votingQuestions;
Probably use a Set instead, if we don't rely on the database order.

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/error/ErrorCode.java
> +  VOTE_ALREADY_ENDED(176, "You can not vote if the voting has not already finished", "Vote ended at ''{0}''"),
second not is wrong

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/error/ErrorCode.java
> +  MAL_FORMATTED_ALTERNATIVE_ORDINALS(177, "You have mal formatted alternative ordinals", "Check your preference ordinals");
malformatted is one word

2018-06-02 14:18 UTC, Brutus5000 commented on src/main/java/com/faforever/api/voting/VoteRepository.java
> +  List<Vote> findByVotingSubject(VotingSubject votingSubject);
Probably use a Set instead, if we don't rely on the database order.

2018-06-02 22:20 UTC, Brutus5000 requested changes
I stumbled on some more things.

2018-06-03 13:41 UTC, axel1200 commented on src/main/java/com/faforever/api/voting/VotingService.java
> +    vote.getVotingAnswers().forEach(votingAnswer -> {
Yes the user needs to specify all the data in his post, like this we only expect the object to have an id, all the rest is filled up with the data from the database

2018-06-03 21:40 UTC, micheljung requested changes

2018-06-03 21:40 UTC, micheljung commented on src/main/java/com/faforever/api/voting/VotingController.java
> +      response.sendRedirect(String.format("/data/votingSubject?%s&filter=%s", queryString, filter.toString()));
`.toString()` is unnecessary and preferably, we'd use `UriComponentsBuilder` to build the string (but I'm not expecting you to use it here)

2018-06-03 21:40 UTC, micheljung commented on src/main/java/com/faforever/api/voting/VotingService.java
> +      long count = vote.getVotingAnswers().stream().filter(votingAnswer1 -> votingAnswer1.getVotingChoice().equals(votingAnswer.getVotingChoice())).count();
Please use newlines in stream chains, like so:
```
long count = vote.getVotingAnswers().stream()
  .filter(votingAnswer1 -> votingAnswer1.getVotingChoice().equals(votingAnswer.getVotingChoice()))
  .count();
```

2018-06-04 17:34 UTC, axel1200 commented on src/main/java/com/faforever/api/data/domain/VotingAnswer.java
> +  private int alternativeOrdinal;
Good that you learned that

2018-06-04 17:37 UTC, axel1200 commented on src/main/java/com/faforever/api/data/listeners/VotingQuestionEnricher.java
> +          .filter(votingAnswer1 -> votingAnswer1.getVotingChoice().getVotingQuestion().equals(votingAnswer.getVotingChoice().getVotingQuestion()) && votingAnswer1.getAlternativeOrdinal() == newAltern
Does not work it does not know id

2018-06-05 17:18 UTC, micheljung approved these changes

2018-06-05 17:18 UTC, merged