Fixes #252
micheljung/faf-java-api pull request #256
Opened 2018-09-07 17:48 UTC by axel1200

2018-09-08 20:36 UTC, Brutus5000 requested changes
Stop removing the throws Exception from the unit tests. This is very annoying to review and it also doesn't make life easier. You add this to all unit tests because you don't care about exceptions (-> the test would fail anyway) but some test operations have checked exceptions like asserts regarding Jackson.

2018-09-08 22:42 UTC, Brutus5000 submitted a review, later dismissed
The current unit test error indicates we are returning the error json as url parameter. I can't find whether it was introduced by your changes but it can't stay that way.

2018-09-09 11:58 UTC, axel1200 commented
It was introduced by me I will fix it.
It is my IDE that removes those throws Exceptions. And I don't see a problem there be can add it at those test that need it and leave it out for the others.

2018-09-16 17:57 UTC, Brutus5000 approved these changes

2018-09-16 17:57 UTC, merged