Closes #247 Add healthcheck
micheljung/faf-java-api pull request #284
Opened 2018-11-04 13:54 UTC by bukajsytlos

Closes #247 Add healthcheck

2018-11-04 14:11 UTC, bukajsytlos commented
https://github.com/FAForever/faf-stack/issues/56

2018-11-04 14:56 UTC, bukajsytlos commented
https://github.com/FAForever/faf-stack/pull/58

2018-11-04 21:16 UTC, Brutus5000 requested changes

2018-11-04 21:16 UTC, Brutus5000 commented on src/main/resources/config/application-dev.yml
> +        password: ${ADMIN_SERVER_PASSWORD:secret}
We should keep our `banana` policy. All passwords on dev should be banana.

2018-11-12 22:19 UTC, Brutus5000 approved these changes

2018-11-12 22:20 UTC, merged