Enhance avatar urls on upload (encode url) #368
micheljung/faf-java-api pull request #397
Opened 2020-06-01 01:23 UTC by ahsanbagwan

Changes:
- JPA entity and repository
- Avatar Service layer
- Properties file
- Test files
- Test schema

2020-06-01 08:05 UTC, bukajsytlos requested changes

2020-06-01 08:05 UTC, bukajsytlos commented on src/main/java/com/faforever/api/data/domain/Avatar.java
> +import org.springframework.data.annotation.Transient;
javax.persistence.Transient is the correct one

2020-06-01 08:05 UTC, bukajsytlos commented on src/main/java/com/faforever/api/avatar/AvatarRepository.java
> +  //Optional<Avatar> findOneByUrl(String url);
we don't leave any commented code

2020-06-01 08:05 UTC, bukajsytlos commented on src/main/java/com/faforever/api/avatar/AvatarService.java
> +    String url = String.format(properties.getAvatar().getBaseUrl(), normalizedAvatarFileName);
I not sure if this should be here. This is only during creation, but we should compute this attribute at read time also. see comment below

2020-06-01 08:05 UTC, bukajsytlos commented on src/main/java/com/faforever/api/data/domain/Avatar.java
>    public String getUrl() {
I think this should be made @ComputedAttribute and being enriched by EntityLister. Take a look at Clan class and ClanEnricherListener

2020-06-01 08:09 UTC, bukajsytlos requested changes
You should also rebase this on (latest) develop branch

2020-06-11 20:36 UTC, norraxx commented on src/inttest/resources/sql/prepAvatarData.sql
> +SET FOREIGN_KEY_CHECKS = 1;
:see_no_evil: Truncate didn't work?

2020-06-11 20:50 UTC, Brutus5000 commented on src/inttest/resources/sql/prepAvatarData.sql
> +SET FOREIGN_KEY_CHECKS = 1;
I'm tired figuring out the right order.

2020-06-20 17:32 UTC, bukajsytlos approved these changes

2020-06-20 21:23 UTC, Brutus5000 approved these changes

2020-06-20 21:24 UTC, merged