Add update permission on GroupPermission UserGroups
micheljung/faf-java-api pull request #501
Opened 2021-09-25 18:43 UTC by Sheikah45

Allows updating group permissions tied to https://github.com/FAForever/faf-moderator-client/pull/135

2021-09-25 21:54 UTC, Brutus5000 reviewed
Hmm I would have expected that we need @Update permissions on user_group_assignment and group_permission_assignment and  not on the GroupPermission class  relationship

2021-09-25 22:21 UTC, Sheikah45 commented
There is no individual classes for the assignments though. They are propagated directly to the userGroup and groupPermission objects as far as I can tell. And since the userGroup is the owning entity any changes there get cascaded to the groupPermission.

Also the assignments would already be covered by the @Update on userGroup. I could be missing something though.

2021-09-25 22:23 UTC, Sheikah45 commented
It is because of the 
```
  @ManyToMany(cascade = {
    CascadeType.PERSIST,
    CascadeType.MERGE
  })
```
on the permissions field of UserGroup

2021-09-26 21:53 UTC, Brutus5000 requested changes

2021-09-26 21:53 UTC, Brutus5000 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithoutScope() throws Exception {
UserNote?

2021-09-26 21:53 UTC, Brutus5000 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithoutRole() throws Exception {
UserNote?

2021-09-26 21:53 UTC, Brutus5000 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithScopeAndRole() throws Exception {
UserNote?

2021-09-26 21:53 UTC, Brutus5000 commented on src/inttest/resources/sql/prepDefaultData.sql
> +       (5, 'faf_illuminati', 'user_group.faf.iiluminati', null, false);
typo in iiluminati :stuck_out_tongue:

2021-09-26 21:56 UTC, Sheikah45 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithoutScope() throws Exception {
bad pastaCopy

2021-09-26 22:21 UTC, Sheikah45 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithoutScope() throws Exception {
Fixed

2021-09-26 22:21 UTC, Sheikah45 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithScopeAndRole() throws Exception {
Fixed

2021-09-26 22:21 UTC, Sheikah45 commented on src/inttest/resources/sql/prepDefaultData.sql
> +       (5, 'faf_illuminati', 'user_group.faf.iiluminati', null, false);
Fixed

2021-09-26 22:21 UTC, Sheikah45 commented on src/inttest/java/com/faforever/api/data/GroupPermissionTest.java
> +  public void cannotCreateUserNoteWithoutRole() throws Exception {
Fixed

2021-09-26 22:22 UTC, Brutus5000 approved these changes

2021-09-26 22:27 UTC, merged