Minimum mod name length #232
micheljung/faf-java-api pull request #504
Opened 2021-10-05 16:13 UTC by basalt79

added also the "nil" check and the missing error tests from the TODO 

would be great to get also the `hacktoberfest-accepted` label

2021-10-05 20:52 UTC, Askaholic commented
Make sure to add ‘Closes #232’ to the pr description.

2021-10-06 07:58 UTC, bukajsytlos requested changes

2021-10-06 07:58 UTC, bukajsytlos commented on src/test/java/com/faforever/api/mod/ModServiceTest.java
> +    ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(uploadFile));
please use try-with-resources

2021-10-06 17:50 UTC, basalt79 commented on src/test/java/com/faforever/api/mod/ModServiceTest.java
> +    ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(uploadFile));
@bukajsytlos  updated PR

2021-10-06 18:39 UTC, bukajsytlos submitted a review, later dismissed

2021-10-09 11:03 UTC, Brutus5000 commented on src/main/java/com/faforever/api/mod/ModService.java
> +      .setRecommended(false);
formatting broke here

2021-10-09 11:04 UTC, Brutus5000 commented on src/test/java/com/faforever/api/mod/ModServiceTest.java
> +  private ModService service;
the name `instance` is a convention (in this project). please keep it

2021-10-10 11:22 UTC, basalt79 commented on src/test/java/com/faforever/api/mod/ModServiceTest.java
> +  private ModService service;
reverted name

2021-10-10 12:31 UTC, bukajsytlos commented on src/main/java/com/faforever/api/mod/ModService.java
> +      .setRecommended(false);
it is not on the same level

2021-10-17 14:16 UTC, bukajsytlos approved these changes
lgtm

2021-10-21 05:04 UTC, merged