Closes #820 Improve handling of failed steam redirect validations #820
micheljung/faf-java-api pull request #822
Opened 2024-01-13 22:02 UTC by Ivan-Shaml

2024-01-14 21:17 UTC, Brutus5000 requested changes
Looks good, just 2 minor change requests :D

2024-01-14 21:17 UTC, Brutus5000 commented on src/main/java/com/faforever/api/user/SteamService.java
> +      );
Please adjust formatting so we have on call per line

```
accountLinkRepository.findOneByServiceIdAndServiceType(...)
  .map(...)
  .ifPresentOrElse(...)
```

2024-01-14 21:17 UTC, Brutus5000 commented on src/main/java/com/faforever/api/user/SteamService.java
> +    } else {
The `containsIdentityParam` check could be moved into `parseSteamIdFromLoginRedirect` which would then return an Optional.
Then here we could just `.orElseThrow()`

2024-01-15 17:47 UTC, Ivan-Shaml commented on src/main/java/com/faforever/api/user/SteamService.java
> +    } else {
The `com.faforever.api.user.SteamService#parseSteamIdFromLoginRedirect` method is used directly in the UsersController as well:
 - `com.faforever.api.user.UsersController#requestPasswordResetViaSteam`
 - `com.faforever.api.user.UsersController#linkToSteam`

Wouldn't it be nicer that if the loging + throwing an exception (if identityParam is not contained) get moved inside of the method, because if we make the method to return an Optional, we would need to handle that  the same way on multiple places.

Also with the current implementation of the method if the `openid.identity` parameter is not contained within the request (`request.getParameter("openid.identity")` returns `null`,  we call `.subsring` on `null`, so there is a NPE), definitely the whole method `parseSteamIdFromLoginRedirect` should be revisited anyway ...

2024-01-15 19:25 UTC, Brutus5000 approved these changes

2024-01-15 19:26 UTC, merged