adding fields for #894
micheljung/faf-java-api pull request #896
Opened 2024-10-12 17:47 UTC by K-ETFreeman

solves #894

2024-10-14 15:54 UTC, Sheikah45 approved these changes

2024-10-14 15:55 UTC, Sheikah45 requested changes, later dismissed
Can you add the integration tests to check the permissions for updates works for these fields.

2024-11-24 12:44 UTC, K-ETFreeman commented
> Can you add the integration tests to check the permissions for updates works for these fields.

You mean writing another .java file like this?
![image](https://github.com/user-attachments/assets/a7370bb1-c604-41ea-ad3c-cbf2f28cc96f)
MatchmakerQueueMapPoolElideTest.java?

2024-11-24 12:47 UTC, Sheikah45 commented
Yes

2024-11-24 12:54 UTC, K-ETFreeman commented
> MatchmakerQueueMapPoolElideTest.java

i also should probably write prepMatchmakerQueueMapPoolData.sql then

2024-11-24 12:55 UTC, K-ETFreeman commented
seeing -- matchmaker_queue is populated by R__070_matchmaker_queue.sql from Flyway comment tho, not sure

2024-11-24 14:28 UTC, K-ETFreeman commented
> Yes

![image](https://github.com/user-attachments/assets/4c42ca0c-5d80-4495-b57a-51017a77a4dc)
hm
where API gets data about db schema? i was thinking from commons but seems like not

2024-11-25 14:25 UTC, Brutus5000 commented
https://github.com/FAForever/faf-java-api/blob/ef26b9c89ef0ee2d41d5168342d1c088a3cae491/src/inttest/java/com/faforever/api/config/MainDbTestContainers.java#L24

2024-11-25 14:26 UTC, Brutus5000 commented
And at runtime here https://github.com/FAForever/faf-java-api/blob/ef26b9c89ef0ee2d41d5168342d1c088a3cae491/src/main/resources/config/application.yml#L19

2024-12-03 17:59 UTC, Brutus5000 approved these changes, later dismissed

2024-12-23 19:20 UTC, Brutus5000 commented
I have no clue why the java commons project doesn't work anymore

2024-12-24 16:22 UTC, Ivan-Shaml commented
> I have no clue why the java commons project doesn't work anymore

Hi, I see a pattern here, If you take a look at the recent failing PRs for the `faf-java-api` (e.g. the dependa-bot ones for bumping up spring boot to 3.4.1 and Elide to 7.1.4), they all fail on this particular unit test - `com.faforever.api.deployment.ExeUploaderControllerTest#testBadRequestUploadFileWithWrongExeExtension`

The common between them and this commit is that they bring a change to the class path, by transitively adding a higher version of jackson (this PR as well because it points to a newer version (see the `build.gradle` change) of the `faf-java-commons` which has `jackson = "2.18.2"`, from [this recent PR](https://github.com/FAForever/faf-java-commons/commit/2b98a136bee979891c5221f03dc62a67d3b89349#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR3) in `faf-java-commons`)

The actual issue boils down to, when Jackson tries to serialize the error response JSON produced by the ControllerAdvice/GlobalExceptionHandler -
```java
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had explicit creator [constructor for `com.faforever.api.error.ErrorResult` (5 args), annotations: {interface java.beans.ConstructorProperties=@java.beans.ConstructorProperties({"httpStatusCode", "title", "detail", "appCode", "meta"})}, encountered another: [constructor for `com.faforever.api.error.ErrorResult` (3 args), annotations: {interface java.beans.ConstructorProperties=@java.beans.ConstructorProperties({"httpStatusCode", "title", "detail"})} (through reference chain: com.faforever.api.error.ErrorResponse["errors"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1328)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1475)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:811)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:314)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:115)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1583)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1061)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:486)
	... 153 common frames omitted
```

2024-12-25 21:12 UTC, Ivan-Shaml commented
Fixed the problematic class, from the exception in my previous comment in this new PR - #918
I recommend to rebase the spring boot 3.4 PR and this one, when #918 gets merged

2025-10-03 20:16 UTC, Brutus5000 approved these changes

2025-10-03 22:16 UTC, merged